### ISSUE TITLE
Not and Issue just ask some question :)

### ISSUE THREAD

**Issue by adiramardiani** [Selithrarion/quasar-nest_jira-clone#1]
Hai

Currently I'm learning about vue3 + typescript + quasar, and I found your amazing repository, I like your design pattern, the way you make src/models and src/service is easy to understand

I have some question

1. Why you make interface ProjectModel and ProjectDTO, what the reason ?
2. My background is backend developer (laravel), I have a simple api for blog : post, post_category, tags can you help me make a frontend crud about it

Is there any other way other than issues to communicate with you ?

Thanks :)

**Comment by Selithrarion** [comment]
Hi) glad to hear that))

1. It seemed to me that it would be a good idea to separately describe how the data would look specifically for the request API - they may differ. For example, in ProjectDTO we do not have a users field, because this is managed from the backend and cannot be changed through the frontend, etc. Or are you asking about something else?
2. Of course, how exactly can I help you? Are there any difficulties or questions?

discord - Selithrarion(Sergey)#5794
telegram - selithrarion09
